### ISSUE TITLE
Is there any way to use sqlite3 

### ISSUE THREAD

**Issue by lostfile1** [zrm99/Odalmedia#32]
I've been having issues with postgresql on my machine is there any way i can use sqlite3 instead

**Comment by zrm99** [comment]
Unfortunately with the way the program is written, it is dependent on the 'pg' module in private/database.js and the postgres express-session store in odal.js (connect-pg-simple) , so you would have to rewrite the entire database in sqlite3 for that to work and change the express session store to sqlite3.

All of the current database functions use the pg module which helps to prevent accidental SQL injection vulnerabilites by parameterizing the database queries.

With some effort, it is possible to change the 'pg' module and session store to a sqlite module and to change the postgresql queries with the sqlite equivalent.

I could do this for you specifically with some time, but I do not have access to a computer and I do not know when I will have acess to one, which makes me very limited in my ability to offer detailed help and my ability to do any sort of programming.

**Comment by lostfile1** [comment]
oof
